#!/usr/bin/env bash
# Configures load balancer
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get install -y haproxy=2.0.*
sed -i "$ a frontend local_server\n    bind *:80\n    mode http\n    default_backend servers\nbackend web_servers\n    balance roundrobin\n    server 37876-web-01 52.87.233.143:80 check\n    server 37876-web-02 18.204.13.72:80 check" /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
service haproxy start
